//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Navipro.Infojet.Lib.InfojetServiceRequest {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InfojetServiceRequestSoap", Namespace="http://infojet.workanywhere.se/")]
    public partial class InfojetServiceRequest : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback performserviceOperationCompleted;
        
        private System.Threading.SendOrPostCallback submitOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InfojetServiceRequest() {
            this.Url = global::Navipro.Infojet.Lib.Properties.Settings.Default.InfojetLib_InfojetServiceRequest_InfojetServiceRequest;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event performserviceCompletedEventHandler performserviceCompleted;
        
        /// <remarks/>
        public event submitOrderCompletedEventHandler submitOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://infojet.workanywhere.se/performservice", RequestNamespace="http://infojet.workanywhere.se/", ResponseNamespace="http://infojet.workanywhere.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string performservice(string xmlDoc) {
            object[] results = this.Invoke("performservice", new object[] {
                        xmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void performserviceAsync(string xmlDoc) {
            this.performserviceAsync(xmlDoc, null);
        }
        
        /// <remarks/>
        public void performserviceAsync(string xmlDoc, object userState) {
            if ((this.performserviceOperationCompleted == null)) {
                this.performserviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnperformserviceOperationCompleted);
            }
            this.InvokeAsync("performservice", new object[] {
                        xmlDoc}, this.performserviceOperationCompleted, userState);
        }
        
        private void OnperformserviceOperationCompleted(object arg) {
            if ((this.performserviceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.performserviceCompleted(this, new performserviceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://infojet.workanywhere.se/submitOrder", RequestNamespace="http://infojet.workanywhere.se/", ResponseNamespace="http://infojet.workanywhere.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void submitOrder(string orderNo, WebCartHeader webCartHeader, System.Data.DataSet webCartLinesDataSet) {
            this.Invoke("submitOrder", new object[] {
                        orderNo,
                        webCartHeader,
                        webCartLinesDataSet});
        }
        
        /// <remarks/>
        public void submitOrderAsync(string orderNo, WebCartHeader webCartHeader, System.Data.DataSet webCartLinesDataSet) {
            this.submitOrderAsync(orderNo, webCartHeader, webCartLinesDataSet, null);
        }
        
        /// <remarks/>
        public void submitOrderAsync(string orderNo, WebCartHeader webCartHeader, System.Data.DataSet webCartLinesDataSet, object userState) {
            if ((this.submitOrderOperationCompleted == null)) {
                this.submitOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitOrderOperationCompleted);
            }
            this.InvokeAsync("submitOrder", new object[] {
                        orderNo,
                        webCartHeader,
                        webCartLinesDataSet}, this.submitOrderOperationCompleted, userState);
        }
        
        private void OnsubmitOrderOperationCompleted(object arg) {
            if ((this.submitOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.submitOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://infojet.workanywhere.se/")]
    public partial class WebCartHeader {
        
        private string webCheckoutCodeField;
        
        private string sessionIdField;
        
        private string customerNoField;
        
        private string userAccountNoField;
        
        private string billToNameField;
        
        private string billToName2Field;
        
        private string billToAddressField;
        
        private string billToAddress2Field;
        
        private string billToPostCodeField;
        
        private string billToCityField;
        
        private string billToCountryCodeField;
        
        private bool addShipToAddressField;
        
        private string shipToCodeField;
        
        private string shipToNameField;
        
        private string shipToName2Field;
        
        private string shipToAddressField;
        
        private string shipToAddress2Field;
        
        private string shipToPostCodeField;
        
        private string shipToCityField;
        
        private string shipToCountryCodeField;
        
        private string contactNameField;
        
        private string phoneNoField;
        
        private string emailField;
        
        private string customerOrderNoField;
        
        private string noteOfGoodsField;
        
        private string clientIpAddressField;
        
        private string clientUserAgentField;
        
        private string currencyCodeField;
        
        private string webPaymentMethodCodeField;
        
        private string webShipmentMethodCodeField;
        
        private bool salesTermsConfirmedField;
        
        private string paymentReferenceField;
        
        private string paymentOrderNoField;
        
        private string messageField;
        
        private string shippingAgentCodeField;
        
        private string shippingAgentServiceCodeField;
        
        private string shipmentMethodCodeField;
        
        private string shippingAgentServiceDescriptionField;
        
        private string webSiteCodeField;
        
        private string languageCodeField;
        
        private string shippingAdviceField;
        
        private System.DateTime shipmentDateField;
        
        private float freightFeeField;
        
        private float adminFeeField;
        
        private string campaignCodeField;
        
        private bool pricesInclVatField;
        
        private WebShipmentMethod webShipmentMethodField;
        
        private WebPaymentMethod webPaymentMethodField;
        
        private WebCartField[] extraFieldsField;
        
        /// <remarks/>
        public string webCheckoutCode {
            get {
                return this.webCheckoutCodeField;
            }
            set {
                this.webCheckoutCodeField = value;
            }
        }
        
        /// <remarks/>
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        public string customerNo {
            get {
                return this.customerNoField;
            }
            set {
                this.customerNoField = value;
            }
        }
        
        /// <remarks/>
        public string userAccountNo {
            get {
                return this.userAccountNoField;
            }
            set {
                this.userAccountNoField = value;
            }
        }
        
        /// <remarks/>
        public string billToName {
            get {
                return this.billToNameField;
            }
            set {
                this.billToNameField = value;
            }
        }
        
        /// <remarks/>
        public string billToName2 {
            get {
                return this.billToName2Field;
            }
            set {
                this.billToName2Field = value;
            }
        }
        
        /// <remarks/>
        public string billToAddress {
            get {
                return this.billToAddressField;
            }
            set {
                this.billToAddressField = value;
            }
        }
        
        /// <remarks/>
        public string billToAddress2 {
            get {
                return this.billToAddress2Field;
            }
            set {
                this.billToAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string billToPostCode {
            get {
                return this.billToPostCodeField;
            }
            set {
                this.billToPostCodeField = value;
            }
        }
        
        /// <remarks/>
        public string billToCity {
            get {
                return this.billToCityField;
            }
            set {
                this.billToCityField = value;
            }
        }
        
        /// <remarks/>
        public string billToCountryCode {
            get {
                return this.billToCountryCodeField;
            }
            set {
                this.billToCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool addShipToAddress {
            get {
                return this.addShipToAddressField;
            }
            set {
                this.addShipToAddressField = value;
            }
        }
        
        /// <remarks/>
        public string shipToCode {
            get {
                return this.shipToCodeField;
            }
            set {
                this.shipToCodeField = value;
            }
        }
        
        /// <remarks/>
        public string shipToName {
            get {
                return this.shipToNameField;
            }
            set {
                this.shipToNameField = value;
            }
        }
        
        /// <remarks/>
        public string shipToName2 {
            get {
                return this.shipToName2Field;
            }
            set {
                this.shipToName2Field = value;
            }
        }
        
        /// <remarks/>
        public string shipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
            }
        }
        
        /// <remarks/>
        public string shipToAddress2 {
            get {
                return this.shipToAddress2Field;
            }
            set {
                this.shipToAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string shipToPostCode {
            get {
                return this.shipToPostCodeField;
            }
            set {
                this.shipToPostCodeField = value;
            }
        }
        
        /// <remarks/>
        public string shipToCity {
            get {
                return this.shipToCityField;
            }
            set {
                this.shipToCityField = value;
            }
        }
        
        /// <remarks/>
        public string shipToCountryCode {
            get {
                return this.shipToCountryCodeField;
            }
            set {
                this.shipToCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string contactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        public string phoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string customerOrderNo {
            get {
                return this.customerOrderNoField;
            }
            set {
                this.customerOrderNoField = value;
            }
        }
        
        /// <remarks/>
        public string noteOfGoods {
            get {
                return this.noteOfGoodsField;
            }
            set {
                this.noteOfGoodsField = value;
            }
        }
        
        /// <remarks/>
        public string clientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string clientUserAgent {
            get {
                return this.clientUserAgentField;
            }
            set {
                this.clientUserAgentField = value;
            }
        }
        
        /// <remarks/>
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string webPaymentMethodCode {
            get {
                return this.webPaymentMethodCodeField;
            }
            set {
                this.webPaymentMethodCodeField = value;
            }
        }
        
        /// <remarks/>
        public string webShipmentMethodCode {
            get {
                return this.webShipmentMethodCodeField;
            }
            set {
                this.webShipmentMethodCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool salesTermsConfirmed {
            get {
                return this.salesTermsConfirmedField;
            }
            set {
                this.salesTermsConfirmedField = value;
            }
        }
        
        /// <remarks/>
        public string paymentReference {
            get {
                return this.paymentReferenceField;
            }
            set {
                this.paymentReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string paymentOrderNo {
            get {
                return this.paymentOrderNoField;
            }
            set {
                this.paymentOrderNoField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string shippingAgentCode {
            get {
                return this.shippingAgentCodeField;
            }
            set {
                this.shippingAgentCodeField = value;
            }
        }
        
        /// <remarks/>
        public string shippingAgentServiceCode {
            get {
                return this.shippingAgentServiceCodeField;
            }
            set {
                this.shippingAgentServiceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string shipmentMethodCode {
            get {
                return this.shipmentMethodCodeField;
            }
            set {
                this.shipmentMethodCodeField = value;
            }
        }
        
        /// <remarks/>
        public string shippingAgentServiceDescription {
            get {
                return this.shippingAgentServiceDescriptionField;
            }
            set {
                this.shippingAgentServiceDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string webSiteCode {
            get {
                return this.webSiteCodeField;
            }
            set {
                this.webSiteCodeField = value;
            }
        }
        
        /// <remarks/>
        public string languageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string shippingAdvice {
            get {
                return this.shippingAdviceField;
            }
            set {
                this.shippingAdviceField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime shipmentDate {
            get {
                return this.shipmentDateField;
            }
            set {
                this.shipmentDateField = value;
            }
        }
        
        /// <remarks/>
        public float freightFee {
            get {
                return this.freightFeeField;
            }
            set {
                this.freightFeeField = value;
            }
        }
        
        /// <remarks/>
        public float adminFee {
            get {
                return this.adminFeeField;
            }
            set {
                this.adminFeeField = value;
            }
        }
        
        /// <remarks/>
        public string campaignCode {
            get {
                return this.campaignCodeField;
            }
            set {
                this.campaignCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool pricesInclVat {
            get {
                return this.pricesInclVatField;
            }
            set {
                this.pricesInclVatField = value;
            }
        }
        
        /// <remarks/>
        public WebShipmentMethod webShipmentMethod {
            get {
                return this.webShipmentMethodField;
            }
            set {
                this.webShipmentMethodField = value;
            }
        }
        
        /// <remarks/>
        public WebPaymentMethod webPaymentMethod {
            get {
                return this.webPaymentMethodField;
            }
            set {
                this.webPaymentMethodField = value;
            }
        }
        
        /// <remarks/>
        public WebCartField[] extraFields {
            get {
                return this.extraFieldsField;
            }
            set {
                this.extraFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://infojet.workanywhere.se/")]
    public partial class WebShipmentMethod {
        
        private string webSiteCodeField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string shipmentMethodCodeField;
        
        private string shippingAgentCodeField;
        
        private string shippingAgentServiceCodeField;
        
        private int levelTypeField;
        
        private bool activeField;
        
        private string textField;
        
        private bool defaultValueField;
        
        private string defaultTextField;
        
        private float amountField;
        
        private float amountInclVatField;
        
        private string formatedAmountField;
        
        private string formatedAmountInclVatField;
        
        private string glAccountNoField;
        
        private string vatProdPostingGroupField;
        
        private bool specifyCheckoutsField;
        
        /// <remarks/>
        public string webSiteCode {
            get {
                return this.webSiteCodeField;
            }
            set {
                this.webSiteCodeField = value;
            }
        }
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string shipmentMethodCode {
            get {
                return this.shipmentMethodCodeField;
            }
            set {
                this.shipmentMethodCodeField = value;
            }
        }
        
        /// <remarks/>
        public string shippingAgentCode {
            get {
                return this.shippingAgentCodeField;
            }
            set {
                this.shippingAgentCodeField = value;
            }
        }
        
        /// <remarks/>
        public string shippingAgentServiceCode {
            get {
                return this.shippingAgentServiceCodeField;
            }
            set {
                this.shippingAgentServiceCodeField = value;
            }
        }
        
        /// <remarks/>
        public int levelType {
            get {
                return this.levelTypeField;
            }
            set {
                this.levelTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public bool defaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        public string defaultText {
            get {
                return this.defaultTextField;
            }
            set {
                this.defaultTextField = value;
            }
        }
        
        /// <remarks/>
        public float amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public float amountInclVat {
            get {
                return this.amountInclVatField;
            }
            set {
                this.amountInclVatField = value;
            }
        }
        
        /// <remarks/>
        public string formatedAmount {
            get {
                return this.formatedAmountField;
            }
            set {
                this.formatedAmountField = value;
            }
        }
        
        /// <remarks/>
        public string formatedAmountInclVat {
            get {
                return this.formatedAmountInclVatField;
            }
            set {
                this.formatedAmountInclVatField = value;
            }
        }
        
        /// <remarks/>
        public string glAccountNo {
            get {
                return this.glAccountNoField;
            }
            set {
                this.glAccountNoField = value;
            }
        }
        
        /// <remarks/>
        public string vatProdPostingGroup {
            get {
                return this.vatProdPostingGroupField;
            }
            set {
                this.vatProdPostingGroupField = value;
            }
        }
        
        /// <remarks/>
        public bool specifyCheckouts {
            get {
                return this.specifyCheckoutsField;
            }
            set {
                this.specifyCheckoutsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://infojet.workanywhere.se/")]
    public partial class WebCartField {
        
        private string webFormCodeField;
        
        private string fieldCodeField;
        
        private string descriptionField;
        
        private string valueField;
        
        private bool transferToOrderTextLineField;
        
        /// <remarks/>
        public string webFormCode {
            get {
                return this.webFormCodeField;
            }
            set {
                this.webFormCodeField = value;
            }
        }
        
        /// <remarks/>
        public string fieldCode {
            get {
                return this.fieldCodeField;
            }
            set {
                this.fieldCodeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public bool transferToOrderTextLine {
            get {
                return this.transferToOrderTextLineField;
            }
            set {
                this.transferToOrderTextLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://infojet.workanywhere.se/")]
    public partial class WebPaymentMethod {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void performserviceCompletedEventHandler(object sender, performserviceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class performserviceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal performserviceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void submitOrderCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591