//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarPRNTSDK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarPRNTSDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllReceipts Ext.
        /// </summary>
        public static string AllReceiptsExtSamplePageTitle {
            get {
                return ResourceManager.GetString("AllReceiptsExtSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllReceipts.
        /// </summary>
        public static string AllReceiptsSamplePageTitle {
            get {
                return ResourceManager.GetString("AllReceiptsSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        public static string APISamplePageTitle {
            get {
                return ResourceManager.GetString("APISamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon app_icon {
            get {
                object obj = ResourceManager.GetObject("app_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StarPRNT SDK.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Reader Ext.
        /// </summary>
        public static string BarcodeReaderExtSamplePageTitle {
            get {
                return ResourceManager.GetString("BarcodeReaderExtSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Mark Paste.
        /// </summary>
        public static string BlackMarkPasteSamplePageTitle {
            get {
                return ResourceManager.GetString("BlackMarkPasteSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Mark.
        /// </summary>
        public static string BlackMarkSamplePageTitle {
            get {
                return ResourceManager.GetString("BlackMarkSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Setting.
        /// </summary>
        public static string BluetoothSettingSamplePageTitle {
            get {
                return ResourceManager.GetString("BluetoothSettingSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Drawer Ext.
        /// </summary>
        public static string CashDrawerExtSamplePageTitle {
            get {
                return ResourceManager.GetString("CashDrawerExtSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Drawer.
        /// </summary>
        public static string CashDrawerSamplePageTitle {
            get {
                return ResourceManager.GetString("CashDrawerSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination Ext.
        /// </summary>
        public static string CombinationExtSamplePageTitle {
            get {
                return ResourceManager.GetString("CombinationExtSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination Printer Driver.
        /// </summary>
        public static string CombinationPrinterDriverSamplePageTitle {
            get {
                return ResourceManager.GetString("CombinationPrinterDriverSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination.
        /// </summary>
        public static string CombinationSamplePageTitle {
            get {
                return ResourceManager.GetString("CombinationSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coupon_image {
            get {
                object obj = ResourceManager.GetObject("coupon_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_french {
            get {
                object obj = ResourceManager.GetObject("coupon_image_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_german {
            get {
                object obj = ResourceManager.GetObject("coupon_image_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_japanese {
            get {
                object obj = ResourceManager.GetObject("coupon_image_japanese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_portuguese {
            get {
                object obj = ResourceManager.GetObject("coupon_image_portuguese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_russian {
            get {
                object obj = ResourceManager.GetObject("coupon_image_russian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_simplified_chinese {
            get {
                object obj = ResourceManager.GetObject("coupon_image_simplified_chinese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_spanish {
            get {
                object obj = ResourceManager.GetObject("coupon_image_spanish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_traditional_chinese {
            get {
                object obj = ResourceManager.GetObject("coupon_image_traditional_chinese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Status.
        /// </summary>
        public static string DeviceStatusSamplePageTitle {
            get {
                return ResourceManager.GetString("DeviceStatusSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap display_image_1 {
            get {
                object obj = ResourceManager.GetObject("display_image_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap display_image_2 {
            get {
                object obj = ResourceManager.GetObject("display_image_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap display_image_3 {
            get {
                object obj = ResourceManager.GetObject("display_image_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap display_image_4 {
            get {
                object obj = ResourceManager.GetObject("display_image_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Ext.
        /// </summary>
        public static string DisplayExtSamplePageTitle {
            get {
                return ResourceManager.GetString("DisplayExtSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string DisplaySamplePageTitle {
            get {
                return ResourceManager.GetString("DisplaySamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap launch_image {
            get {
                object obj = ResourceManager.GetObject("launch_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Mode.
        /// </summary>
        public static string PageModeSamplePageTitle {
            get {
                return ResourceManager.GetString("PageModeSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Driver with Barcode Reader.
        /// </summary>
        public static string PrinterDriverWithBarcodeReaderSamplePageTitle {
            get {
                return ResourceManager.GetString("PrinterDriverWithBarcodeReaderSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Driver with Check Status.
        /// </summary>
        public static string PrinterDriverWithCheckStatusSamplePageTitle {
            get {
                return ResourceManager.GetString("PrinterDriverWithCheckStatusSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Driver with Display.
        /// </summary>
        public static string PrinterDriverWithDisplaySamplePageTitle {
            get {
                return ResourceManager.GetString("PrinterDriverWithDisplaySamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Driver with Scale.
        /// </summary>
        public static string PrinterDriverWithScaleSamplePageTitle {
            get {
                return ResourceManager.GetString("PrinterDriverWithScaleSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Ext.
        /// </summary>
        public static string PrinterExtSamplePageTitle {
            get {
                return ResourceManager.GetString("PrinterExtSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string PrinterSamplePageTitle {
            get {
                return ResourceManager.GetString("PrinterSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Refresh_Image {
            get {
                object obj = ResourceManager.GetObject("Refresh_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Ext.
        /// </summary>
        public static string ScaleExtSamlePageTitle {
            get {
                return ResourceManager.GetString("ScaleExtSamlePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string ScaleSamplePageTitle {
            get {
                return ResourceManager.GetString("ScaleSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Port.
        /// </summary>
        public static string SearchPortSamplePageTitle {
            get {
                return ResourceManager.GetString("SearchPortSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sphere_image {
            get {
                object obj = ResourceManager.GetObject("sphere_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap star_logo_image {
            get {
                object obj = ResourceManager.GetObject("star_logo_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like a StarIoExtManager Sample.
        /// </summary>
        public static string StarIOExtManagerSampleTitle {
            get {
                return ResourceManager.GetString("StarIOExtManagerSampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like a StarIO-SDK Sample.
        /// </summary>
        public static string StarIOSDKSampleTitle {
            get {
                return ResourceManager.GetString("StarIOSDKSampleTitle", resourceCulture);
            }
        }
    }
}
