//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2443
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2443.
// 
namespace NavisionConnector.se.navipro.dev1 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QuiksilverSoap", Namespace="http://tempuri.org/")]
    public class Quiksilver : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Quiksilver() {
            this.Url = "http://dev1.navipro.se/SantaMonica/Quiksilver.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAvailableShipments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getAvailableShipments() {
            object[] results = this.Invoke("getAvailableShipments", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAvailableShipments(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAvailableShipments", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetAvailableShipments(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getShipmentLines", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getShipmentLines(string shipmentNo) {
            object[] results = this.Invoke("getShipmentLines", new object[] {
                        shipmentNo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetShipmentLines(string shipmentNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getShipmentLines", new object[] {
                        shipmentNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetShipmentLines(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getShipmentLineIds", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getShipmentLineIds(string shipmentNo, int shipmentLineNo) {
            object[] results = this.Invoke("getShipmentLineIds", new object[] {
                        shipmentNo,
                        shipmentLineNo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetShipmentLineIds(string shipmentNo, int shipmentLineNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getShipmentLineIds", new object[] {
                        shipmentNo,
                        shipmentLineNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetShipmentLineIds(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setShipmentStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setShipmentStatus(string shipmentNo, int status) {
            this.Invoke("setShipmentStatus", new object[] {
                        shipmentNo,
                        status});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetShipmentStatus(string shipmentNo, int status, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setShipmentStatus", new object[] {
                        shipmentNo,
                        status}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetShipmentStatus(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOrganizationInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getOrganizationInfo(string organizationNo, ref string userName, ref string passWord) {
            object[] results = this.Invoke("getOrganizationInfo", new object[] {
                        organizationNo,
                        userName,
                        passWord});
            userName = ((string)(results[0]));
            passWord = ((string)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetOrganizationInfo(string organizationNo, string userName, string passWord, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getOrganizationInfo", new object[] {
                        organizationNo,
                        userName,
                        passWord}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndgetOrganizationInfo(System.IAsyncResult asyncResult, out string userName, out string passWord) {
            object[] results = this.EndInvoke(asyncResult);
            userName = ((string)(results[0]));
            passWord = ((string)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOrganizations", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getOrganizations(string syncGroupCode) {
            object[] results = this.Invoke("getOrganizations", new object[] {
                        syncGroupCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetOrganizations(string syncGroupCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getOrganizations", new object[] {
                        syncGroupCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetOrganizations(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateCustomer(string xmlRecord, string organizationNo) {
            this.Invoke("updateCustomer", new object[] {
                        xmlRecord,
                        organizationNo});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateCustomer(string xmlRecord, string organizationNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateCustomer", new object[] {
                        xmlRecord,
                        organizationNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdateCustomer(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateItem(string xmlRecord) {
            this.Invoke("updateItem", new object[] {
                        xmlRecord});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateItem(string xmlRecord, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateItem", new object[] {
                        xmlRecord}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdateItem(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateItemPrice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateItemPrice(string xmlRecord) {
            this.Invoke("updateItemPrice", new object[] {
                        xmlRecord});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateItemPrice(string xmlRecord, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateItemPrice", new object[] {
                        xmlRecord}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdateItemPrice(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateItemPriceExtended", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateItemPriceExtended(string xmlRecord) {
            this.Invoke("updateItemPriceExtended", new object[] {
                        xmlRecord});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateItemPriceExtended(string xmlRecord, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateItemPriceExtended", new object[] {
                        xmlRecord}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdateItemPriceExtended(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updatePurchasePrice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updatePurchasePrice(string xmlRecord) {
            this.Invoke("updatePurchasePrice", new object[] {
                        xmlRecord});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdatePurchasePrice(string xmlRecord, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updatePurchasePrice", new object[] {
                        xmlRecord}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdatePurchasePrice(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateShippingCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateShippingCustomer(string xmlRecord) {
            this.Invoke("updateShippingCustomer", new object[] {
                        xmlRecord});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateShippingCustomer(string xmlRecord, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateShippingCustomer", new object[] {
                        xmlRecord}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdateShippingCustomer(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUpdatedCustomers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getUpdatedCustomers() {
            object[] results = this.Invoke("getUpdatedCustomers", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUpdatedCustomers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUpdatedCustomers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetUpdatedCustomers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setCustomerUpdated", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setCustomerUpdated(string organizationNo, string customerNo, bool updated) {
            this.Invoke("setCustomerUpdated", new object[] {
                        organizationNo,
                        customerNo,
                        updated});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetCustomerUpdated(string organizationNo, string customerNo, bool updated, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setCustomerUpdated", new object[] {
                        organizationNo,
                        customerNo,
                        updated}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetCustomerUpdated(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getScaleEntries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getScaleEntries() {
            object[] results = this.Invoke("getScaleEntries", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetScaleEntries(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getScaleEntries", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetScaleEntries(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setScaleEntryStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setScaleEntryStatus(string factoryCode, int entryNo, int status) {
            this.Invoke("setScaleEntryStatus", new object[] {
                        factoryCode,
                        entryNo,
                        status});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetScaleEntryStatus(string factoryCode, int entryNo, int status, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setScaleEntryStatus", new object[] {
                        factoryCode,
                        entryNo,
                        status}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetScaleEntryStatus(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getFactoryOrderEntries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getFactoryOrderEntries() {
            object[] results = this.Invoke("getFactoryOrderEntries", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetFactoryOrderEntries(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getFactoryOrderEntries", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetFactoryOrderEntries(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setFactoryOrderEntryStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setFactoryOrderEntryStatus(int entryNo, int status) {
            this.Invoke("setFactoryOrderEntryStatus", new object[] {
                        entryNo,
                        status});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetFactoryOrderEntryStatus(int entryNo, int status, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setFactoryOrderEntryStatus", new object[] {
                        entryNo,
                        status}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetFactoryOrderEntryStatus(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
}
