//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Navipro.SantaMonica.Goldfinger {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GoldfingerSoap", Namespace="http://santamonica.navipro.se/goldfinger")]
    public class Goldfinger : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Goldfinger() {
            this.Url = "http://dev1.navipro.se/SantaMonica/Goldfinger.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/reportStatus", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int reportStatus(string agentCode, int rt90x, int rt90y, System.Single heading, System.Single speed, System.Single height, int status) {
            object[] results = this.Invoke("reportStatus", new object[] {
                        agentCode,
                        rt90x,
                        rt90y,
                        heading,
                        speed,
                        height,
                        status});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreportStatus(string agentCode, int rt90x, int rt90y, System.Single heading, System.Single speed, System.Single height, int status, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reportStatus", new object[] {
                        agentCode,
                        rt90x,
                        rt90y,
                        heading,
                        speed,
                        height,
                        status}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndreportStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/reportStatusEx", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int reportStatusEx(string agentCode, int rt90x, int rt90y, System.Single heading, System.Single speed, System.Single height, int status, string userName) {
            object[] results = this.Invoke("reportStatusEx", new object[] {
                        agentCode,
                        rt90x,
                        rt90y,
                        heading,
                        speed,
                        height,
                        status,
                        userName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreportStatusEx(string agentCode, int rt90x, int rt90y, System.Single heading, System.Single speed, System.Single height, int status, string userName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reportStatusEx", new object[] {
                        agentCode,
                        rt90x,
                        rt90y,
                        heading,
                        speed,
                        height,
                        status,
                        userName}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndreportStatusEx(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/reportStatusTrip", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int reportStatusTrip(string agentCode, int rt90x, int rt90y, System.Single heading, System.Single speed, System.Single height, int status, string userName, int tripMeter) {
            object[] results = this.Invoke("reportStatusTrip", new object[] {
                        agentCode,
                        rt90x,
                        rt90y,
                        heading,
                        speed,
                        height,
                        status,
                        userName,
                        tripMeter});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreportStatusTrip(string agentCode, int rt90x, int rt90y, System.Single heading, System.Single speed, System.Single height, int status, string userName, int tripMeter, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reportStatusTrip", new object[] {
                        agentCode,
                        rt90x,
                        rt90y,
                        heading,
                        speed,
                        height,
                        status,
                        userName,
                        tripMeter}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndreportStatusTrip(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/getSynchEntry", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getSynchEntry(string agentCode, ref int type, ref int action, ref string primaryKey, ref int synchEntryNo) {
            object[] results = this.Invoke("getSynchEntry", new object[] {
                        agentCode,
                        type,
                        action,
                        primaryKey,
                        synchEntryNo});
            type = ((int)(results[1]));
            action = ((int)(results[2]));
            primaryKey = ((string)(results[3]));
            synchEntryNo = ((int)(results[4]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSynchEntry(string agentCode, int type, int action, string primaryKey, int synchEntryNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSynchEntry", new object[] {
                        agentCode,
                        type,
                        action,
                        primaryKey,
                        synchEntryNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetSynchEntry(System.IAsyncResult asyncResult, out int type, out int action, out string primaryKey, out int synchEntryNo) {
            object[] results = this.EndInvoke(asyncResult);
            type = ((int)(results[1]));
            action = ((int)(results[2]));
            primaryKey = ((string)(results[3]));
            synchEntryNo = ((int)(results[4]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/setShipOrderStatus", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setShipOrderStatus(string agentCode, string no, int status, int positionX, int positionY) {
            this.Invoke("setShipOrderStatus", new object[] {
                        agentCode,
                        no,
                        status,
                        positionX,
                        positionY});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetShipOrderStatus(string agentCode, string no, int status, int positionX, int positionY, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setShipOrderStatus", new object[] {
                        agentCode,
                        no,
                        status,
                        positionX,
                        positionY}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetShipOrderStatus(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/setShipOrderStatusEx", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setShipOrderStatusEx(string agentCode, string no, int status, int positionX, int positionY, System.DateTime shipTime) {
            this.Invoke("setShipOrderStatusEx", new object[] {
                        agentCode,
                        no,
                        status,
                        positionX,
                        positionY,
                        shipTime});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetShipOrderStatusEx(string agentCode, string no, int status, int positionX, int positionY, System.DateTime shipTime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setShipOrderStatusEx", new object[] {
                        agentCode,
                        no,
                        status,
                        positionX,
                        positionY,
                        shipTime}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetShipOrderStatusEx(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/setLineOrderStatus", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setLineOrderStatus(string agentCode, string no, int status, int positionX, int positionY, System.DateTime shipTime) {
            this.Invoke("setLineOrderStatus", new object[] {
                        agentCode,
                        no,
                        status,
                        positionX,
                        positionY,
                        shipTime});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetLineOrderStatus(string agentCode, string no, int status, int positionX, int positionY, System.DateTime shipTime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setLineOrderStatus", new object[] {
                        agentCode,
                        no,
                        status,
                        positionX,
                        positionY,
                        shipTime}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetLineOrderStatus(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/setLineOrderStatusEx", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setLineOrderStatusEx(string agentCode, string no, int status, int positionX, int positionY, System.DateTime shipTime, int loadWaitTime) {
            this.Invoke("setLineOrderStatusEx", new object[] {
                        agentCode,
                        no,
                        status,
                        positionX,
                        positionY,
                        shipTime,
                        loadWaitTime});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetLineOrderStatusEx(string agentCode, string no, int status, int positionX, int positionY, System.DateTime shipTime, int loadWaitTime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setLineOrderStatusEx", new object[] {
                        agentCode,
                        no,
                        status,
                        positionX,
                        positionY,
                        shipTime,
                        loadWaitTime}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetLineOrderStatusEx(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/createShipment", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createShipment(string agentCode, System.Data.DataSet shipmentHeaderDataSet, System.Data.DataSet shipmentLinesDataSet, System.Data.DataSet shipmentLineIdsDataSet) {
            this.Invoke("createShipment", new object[] {
                        agentCode,
                        shipmentHeaderDataSet,
                        shipmentLinesDataSet,
                        shipmentLineIdsDataSet});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateShipment(string agentCode, System.Data.DataSet shipmentHeaderDataSet, System.Data.DataSet shipmentLinesDataSet, System.Data.DataSet shipmentLineIdsDataSet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createShipment", new object[] {
                        agentCode,
                        shipmentHeaderDataSet,
                        shipmentLinesDataSet,
                        shipmentLineIdsDataSet}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndcreateShipment(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/createOrder", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createOrder(string agentCode, System.Data.DataSet shipmentHeaderDataSet, System.Data.DataSet shipmentLinesDataSet, System.Data.DataSet shipmentLineIdsDataSet) {
            this.Invoke("createOrder", new object[] {
                        agentCode,
                        shipmentHeaderDataSet,
                        shipmentLinesDataSet,
                        shipmentLineIdsDataSet});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateOrder(string agentCode, System.Data.DataSet shipmentHeaderDataSet, System.Data.DataSet shipmentLinesDataSet, System.Data.DataSet shipmentLineIdsDataSet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createOrder", new object[] {
                        agentCode,
                        shipmentHeaderDataSet,
                        shipmentLinesDataSet,
                        shipmentLineIdsDataSet}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndcreateOrder(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/reportLineJournal", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void reportLineJournal(string agentCode, System.Data.DataSet lineJournalDataSet) {
            this.Invoke("reportLineJournal", new object[] {
                        agentCode,
                        lineJournalDataSet});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreportLineJournal(string agentCode, System.Data.DataSet lineJournalDataSet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reportLineJournal", new object[] {
                        agentCode,
                        lineJournalDataSet}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndreportLineJournal(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/setMessageStatus", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setMessageStatus(string agentCode, int messageEntryNo, int status) {
            this.Invoke("setMessageStatus", new object[] {
                        agentCode,
                        messageEntryNo,
                        status});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetMessageStatus(string agentCode, int messageEntryNo, int status, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setMessageStatus", new object[] {
                        agentCode,
                        messageEntryNo,
                        status}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetMessageStatus(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/ackSynchEntry", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ackSynchEntry(int synchEntryNo) {
            this.Invoke("ackSynchEntry", new object[] {
                        synchEntryNo});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginackSynchEntry(int synchEntryNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ackSynchEntry", new object[] {
                        synchEntryNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndackSynchEntry(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/assignShipOrder", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void assignShipOrder(string agentCode, string no, string newAgentCode) {
            this.Invoke("assignShipOrder", new object[] {
                        agentCode,
                        no,
                        newAgentCode});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginassignShipOrder(string agentCode, string no, string newAgentCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("assignShipOrder", new object[] {
                        agentCode,
                        no,
                        newAgentCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndassignShipOrder(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/reportError", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void reportError(string agentCode, string message) {
            this.Invoke("reportError", new object[] {
                        agentCode,
                        message});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreportError(string agentCode, string message, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reportError", new object[] {
                        agentCode,
                        message}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndreportError(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/createContainerEntry", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createContainerEntry(string agentCode, System.Data.DataSet containerEntryDataSet) {
            this.Invoke("createContainerEntry", new object[] {
                        agentCode,
                        containerEntryDataSet});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateContainerEntry(string agentCode, System.Data.DataSet containerEntryDataSet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createContainerEntry", new object[] {
                        agentCode,
                        containerEntryDataSet}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndcreateContainerEntry(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/setFactoryOrderStatus", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setFactoryOrderStatus(string agentCode, System.Data.DataSet factoryOrderDataSet) {
            this.Invoke("setFactoryOrderStatus", new object[] {
                        agentCode,
                        factoryOrderDataSet});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetFactoryOrderStatus(string agentCode, System.Data.DataSet factoryOrderDataSet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setFactoryOrderStatus", new object[] {
                        agentCode,
                        factoryOrderDataSet}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetFactoryOrderStatus(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/getPriceUpdateItemNo", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPriceUpdateItemNo(string agentCode) {
            object[] results = this.Invoke("getPriceUpdateItemNo", new object[] {
                        agentCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPriceUpdateItemNo(string agentCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPriceUpdateItemNo", new object[] {
                        agentCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPriceUpdateItemNo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://santamonica.navipro.se/goldfinger/acknowledgePriceUpdate", RequestNamespace="http://santamonica.navipro.se/goldfinger", ResponseNamespace="http://santamonica.navipro.se/goldfinger", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void acknowledgePriceUpdate(string agentCode, string itemNo, System.Single checksum) {
            this.Invoke("acknowledgePriceUpdate", new object[] {
                        agentCode,
                        itemNo,
                        checksum});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginacknowledgePriceUpdate(string agentCode, string itemNo, System.Single checksum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("acknowledgePriceUpdate", new object[] {
                        agentCode,
                        itemNo,
                        checksum}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndacknowledgePriceUpdate(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
}
