//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarPRNTSDK.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarPRNTSDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AllReceipts Ext に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllReceiptsExtSamplePageTitle {
            get {
                return ResourceManager.GetString("AllReceiptsExtSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AllReceipts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllReceiptsSamplePageTitle {
            get {
                return ResourceManager.GetString("AllReceiptsSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string APISamplePageTitle {
            get {
                return ResourceManager.GetString("APISamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon app_icon {
            get {
                object obj = ResourceManager.GetObject("app_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   StarPRNT SDK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Barcode Reader Ext に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BarcodeReaderExtSamplePageTitle {
            get {
                return ResourceManager.GetString("BarcodeReaderExtSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black Mark Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlackMarkPasteSamplePageTitle {
            get {
                return ResourceManager.GetString("BlackMarkPasteSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black Mark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlackMarkSamplePageTitle {
            get {
                return ResourceManager.GetString("BlackMarkSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bluetooth Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BluetoothSettingSamplePageTitle {
            get {
                return ResourceManager.GetString("BluetoothSettingSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cash Drawer Ext に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CashDrawerExtSamplePageTitle {
            get {
                return ResourceManager.GetString("CashDrawerExtSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cash Drawer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CashDrawerSamplePageTitle {
            get {
                return ResourceManager.GetString("CashDrawerSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combination Ext に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CombinationExtSamplePageTitle {
            get {
                return ResourceManager.GetString("CombinationExtSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combination Printer Driver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CombinationPrinterDriverSamplePageTitle {
            get {
                return ResourceManager.GetString("CombinationPrinterDriverSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combination に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CombinationSamplePageTitle {
            get {
                return ResourceManager.GetString("CombinationSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap coupon_image {
            get {
                object obj = ResourceManager.GetObject("coupon_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_french {
            get {
                object obj = ResourceManager.GetObject("coupon_image_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_german {
            get {
                object obj = ResourceManager.GetObject("coupon_image_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_japanese {
            get {
                object obj = ResourceManager.GetObject("coupon_image_japanese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_portuguese {
            get {
                object obj = ResourceManager.GetObject("coupon_image_portuguese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_russian {
            get {
                object obj = ResourceManager.GetObject("coupon_image_russian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_simplified_chinese {
            get {
                object obj = ResourceManager.GetObject("coupon_image_simplified_chinese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_spanish {
            get {
                object obj = ResourceManager.GetObject("coupon_image_spanish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap coupon_image_traditional_chinese {
            get {
                object obj = ResourceManager.GetObject("coupon_image_traditional_chinese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Device Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeviceStatusSamplePageTitle {
            get {
                return ResourceManager.GetString("DeviceStatusSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap display_image_1 {
            get {
                object obj = ResourceManager.GetObject("display_image_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap display_image_2 {
            get {
                object obj = ResourceManager.GetObject("display_image_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap display_image_3 {
            get {
                object obj = ResourceManager.GetObject("display_image_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap display_image_4 {
            get {
                object obj = ResourceManager.GetObject("display_image_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Display Ext に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayExtSamplePageTitle {
            get {
                return ResourceManager.GetString("DisplayExtSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplaySamplePageTitle {
            get {
                return ResourceManager.GetString("DisplaySamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap launch_image {
            get {
                object obj = ResourceManager.GetObject("launch_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Page Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageModeSamplePageTitle {
            get {
                return ResourceManager.GetString("PageModeSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Printer Driver with Barcode Reader に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrinterDriverWithBarcodeReaderSamplePageTitle {
            get {
                return ResourceManager.GetString("PrinterDriverWithBarcodeReaderSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Printer Driver with Check Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrinterDriverWithCheckStatusSamplePageTitle {
            get {
                return ResourceManager.GetString("PrinterDriverWithCheckStatusSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Printer Driver with Display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrinterDriverWithDisplaySamplePageTitle {
            get {
                return ResourceManager.GetString("PrinterDriverWithDisplaySamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Printer Driver with Scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrinterDriverWithScaleSamplePageTitle {
            get {
                return ResourceManager.GetString("PrinterDriverWithScaleSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Printer Ext に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrinterExtSamplePageTitle {
            get {
                return ResourceManager.GetString("PrinterExtSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Printer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrinterSamplePageTitle {
            get {
                return ResourceManager.GetString("PrinterSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Refresh_Image {
            get {
                object obj = ResourceManager.GetObject("Refresh_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Scale Ext に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScaleExtSamlePageTitle {
            get {
                return ResourceManager.GetString("ScaleExtSamlePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScaleSamplePageTitle {
            get {
                return ResourceManager.GetString("ScaleSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchPortSamplePageTitle {
            get {
                return ResourceManager.GetString("SearchPortSamplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap sphere_image {
            get {
                object obj = ResourceManager.GetObject("sphere_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap star_logo_image {
            get {
                object obj = ResourceManager.GetObject("star_logo_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Like a StarIoExtManager Sample に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StarIOExtManagerSampleTitle {
            get {
                return ResourceManager.GetString("StarIOExtManagerSampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Like a StarIO-SDK Sample に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StarIOSDKSampleTitle {
            get {
                return ResourceManager.GetString("StarIOSDKSampleTitle", resourceCulture);
            }
        }
    }
}
