//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navipro.Infojet.WebInterface._taglib {
    
    
    public partial class UserDefined_SENDORDERS_DELIVERY {
        
        /// <summary>
        /// shipToAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate shipToAddress;
        
        /// <summary>
        /// Translate1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate1;
        
        /// <summary>
        /// Translate2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate2;
        
        /// <summary>
        /// Translate3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate3;
        
        /// <summary>
        /// Translate4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate4;
        
        /// <summary>
        /// Translate5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate5;
        
        /// <summary>
        /// Translate6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate6;
        
        /// <summary>
        /// Translate7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate7;
        
        /// <summary>
        /// Translate8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate8;
        
        /// <summary>
        /// shipmentMethodRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater shipmentMethodRepeater;
    }
}
