//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInterface._taglib {
    
    
    public partial class UserDefined_SALESIDINFO {
        
        /// <summary>
        /// groupId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate groupId;
        
        /// <summary>
        /// Translate1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate1;
        
        /// <summary>
        /// Translate4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate4;
        
        /// <summary>
        /// Translate2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate2;
        
        /// <summary>
        /// Translate3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate3;
        
        /// <summary>
        /// salesPerson control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate salesPerson;
        
        /// <summary>
        /// email control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate email;
        
        /// <summary>
        /// phoneNo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate phoneNo;
        
        /// <summary>
        /// Translate5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate5;
        
        /// <summary>
        /// Translate6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate6;
        
        /// <summary>
        /// Translate7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Navipro.Infojet.WebInterface._taglib.Translate Translate7;
    }
}
