//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Navipro.SantaMonica.Goldfinger.WebService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ScaleRunnerSoap", Namespace="http://tempuri.org/")]
    public class ScaleRunner : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ScaleRunner() {
            this.Url = "http://dev1.navipro.se/SantaMonica/ScaleRunner.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUnSentFactoryLineJournals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getUnSentFactoryLineJournals(string factoryCode) {
            object[] results = this.Invoke("getUnSentFactoryLineJournals", new object[] {
                        factoryCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUnSentFactoryLineJournals(string factoryCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUnSentFactoryLineJournals", new object[] {
                        factoryCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetUnSentFactoryLineJournals(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLineJournalOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getLineJournalOrders(int lineJournalEntryNo) {
            object[] results = this.Invoke("getLineJournalOrders", new object[] {
                        lineJournalEntryNo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLineJournalOrders(int lineJournalEntryNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLineJournalOrders", new object[] {
                        lineJournalEntryNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetLineJournalOrders(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLineOrderContainers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getLineOrderContainers(int lineOrderEntryNo) {
            object[] results = this.Invoke("getLineOrderContainers", new object[] {
                        lineOrderEntryNo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLineOrderContainers(int lineOrderEntryNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLineOrderContainers", new object[] {
                        lineOrderEntryNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetLineOrderContainers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getContainerEntry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getContainerEntry(string containerNo) {
            object[] results = this.Invoke("getContainerEntry", new object[] {
                        containerNo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetContainerEntry(string containerNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getContainerEntry", new object[] {
                        containerNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetContainerEntry(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setLineJournalAsSent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setLineJournalAsSent(int lineJournalEntryNo) {
            this.Invoke("setLineJournalAsSent", new object[] {
                        lineJournalEntryNo});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetLineJournalAsSent(int lineJournalEntryNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setLineJournalAsSent", new object[] {
                        lineJournalEntryNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetLineJournalAsSent(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setLineOrderContainerWeight", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setLineOrderContainerWeight(int lineOrderEntryNo, string containerNo, System.Single weight, System.DateTime scaledDateTime) {
            this.Invoke("setLineOrderContainerWeight", new object[] {
                        lineOrderEntryNo,
                        containerNo,
                        weight,
                        scaledDateTime});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetLineOrderContainerWeight(int lineOrderEntryNo, string containerNo, System.Single weight, System.DateTime scaledDateTime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setLineOrderContainerWeight", new object[] {
                        lineOrderEntryNo,
                        containerNo,
                        weight,
                        scaledDateTime}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetLineOrderContainerWeight(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getScaleEntries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getScaleEntries(string factoryCode, int status) {
            object[] results = this.Invoke("getScaleEntries", new object[] {
                        factoryCode,
                        status});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetScaleEntries(string factoryCode, int status, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getScaleEntries", new object[] {
                        factoryCode,
                        status}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetScaleEntries(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/createScaleEntry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createScaleEntry(string factoryCode, int type, System.Data.DataSet transactionDataSet) {
            this.Invoke("createScaleEntry", new object[] {
                        factoryCode,
                        type,
                        transactionDataSet});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateScaleEntry(string factoryCode, int type, System.Data.DataSet transactionDataSet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createScaleEntry", new object[] {
                        factoryCode,
                        type,
                        transactionDataSet}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndcreateScaleEntry(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/createScaleEntry2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createScaleEntry2(string factoryCode, int type, System.Data.DataSet transactionDataSet, System.Data.DataSet transactionSubDataSet) {
            this.Invoke("createScaleEntry2", new object[] {
                        factoryCode,
                        type,
                        transactionDataSet,
                        transactionSubDataSet});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateScaleEntry2(string factoryCode, int type, System.Data.DataSet transactionDataSet, System.Data.DataSet transactionSubDataSet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createScaleEntry2", new object[] {
                        factoryCode,
                        type,
                        transactionDataSet,
                        transactionSubDataSet}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndcreateScaleEntry2(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMissingScaleEntries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getMissingScaleEntries(string factoryCode) {
            object[] results = this.Invoke("getMissingScaleEntries", new object[] {
                        factoryCode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetMissingScaleEntries(string factoryCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getMissingScaleEntries", new object[] {
                        factoryCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetMissingScaleEntries(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUnfinishedScaleEntries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getUnfinishedScaleEntries(string factoryCode) {
            object[] results = this.Invoke("getUnfinishedScaleEntries", new object[] {
                        factoryCode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUnfinishedScaleEntries(string factoryCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUnfinishedScaleEntries", new object[] {
                        factoryCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetUnfinishedScaleEntries(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getContainersToScale", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getContainersToScale(string factoryCode) {
            object[] results = this.Invoke("getContainersToScale", new object[] {
                        factoryCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetContainersToScale(string factoryCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getContainersToScale", new object[] {
                        factoryCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetContainersToScale(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLineOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getLineOrder(int lineOrderEntry) {
            object[] results = this.Invoke("getLineOrder", new object[] {
                        lineOrderEntry});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLineOrder(int lineOrderEntry, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLineOrder", new object[] {
                        lineOrderEntry}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetLineOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLineJournal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getLineJournal(int lineJournalEntry, string factoryCode) {
            object[] results = this.Invoke("getLineJournal", new object[] {
                        lineJournalEntry,
                        factoryCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLineJournal(int lineJournalEntry, string factoryCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLineJournal", new object[] {
                        lineJournalEntry,
                        factoryCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetLineJournal(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setContainerAsSent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setContainerAsSent(int lineOrderEntryNo, int lineOrderContainerEntryNo) {
            this.Invoke("setContainerAsSent", new object[] {
                        lineOrderEntryNo,
                        lineOrderContainerEntryNo});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetContainerAsSent(int lineOrderEntryNo, int lineOrderContainerEntryNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setContainerAsSent", new object[] {
                        lineOrderEntryNo,
                        lineOrderContainerEntryNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetContainerAsSent(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLineJournalEntries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getLineJournalEntries(int lineJournalEntryNo) {
            object[] results = this.Invoke("getLineJournalEntries", new object[] {
                        lineJournalEntryNo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLineJournalEntries(int lineJournalEntryNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLineJournalEntries", new object[] {
                        lineJournalEntryNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetLineJournalEntries(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
}
