//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2407.
// 
namespace SmartInventory.se.navipro.dev1 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SynchServiceSoap", Namespace="http://www.navipro.se/navisionmobile/")]
    public class SynchService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SynchService() {
            this.Url = "http://dev1.navipro.se/NavisionMobile/SynchService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.navipro.se/navisionmobile/PerformService", RequestNamespace="http://www.navipro.se/navisionmobile/", ResponseNamespace="http://www.navipro.se/navisionmobile/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PerformService(string serviceRequest) {
            this.Invoke("PerformService", new object[] {
                        serviceRequest});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPerformService(string serviceRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PerformService", new object[] {
                        serviceRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPerformService(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.navipro.se/navisionmobile/PerformServiceEx", RequestNamespace="http://www.navipro.se/navisionmobile/", ResponseNamespace="http://www.navipro.se/navisionmobile/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PerformServiceEx(string serviceRequest) {
            object[] results = this.Invoke("PerformServiceEx", new object[] {
                        serviceRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPerformServiceEx(string serviceRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PerformServiceEx", new object[] {
                        serviceRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndPerformServiceEx(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
